version: '3.3'
services:
  cli:
    image: cornernote/letsencrypt-manager:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/acme-webroot:/var/acme-webroot
      - ./cli.ini:/root/.config/letsencrypt/cli.ini

  cron:
    image: cornernote/letsencrypt-manager:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/acme-webroot:/var/acme-webroot
      - ./cli.ini:/root/.config/letsencrypt/cli.ini
    command: cron-auto-renewal
    restart: always
